### ISSUE TITLE
Handle "line too long"

### ISSUE THREAD

**Issue by arthurlogilab** [myint/docformatter#15]
It would be nice for docformatter to also handle lines that are too long in docstrings

**Comment by myint** [comment]
It currently wraps long lines in some cases. Were you thinking of doing something specific to long lines?

**Comment by arthurlogilab** [comment]
I would expect to have a tool that wraps them at the max line length setting (usually 80 chars). 

Wrapping bullet point lists is a little more tricky that normal paragraphs (indent needs to be right).

**Comment by myint** [comment]
Sorry, I'm not following. It should be wrapping simple cases as [described](https://github.com/myint/docformatter#wrapping-descriptions). Could you provide an example?
