### ISSUE TITLE
No blank line after description should be default mode

### ISSUE THREAD

**Issue by kapsh** [myint/docformatter#19]
Currently docformatter adds a blank line before closing quotes in docstring by default. But this is not conform to actual version of pep-257. 
Commentary about this in `format_docstring` function refers to paragraph which was removed in 2014: https://hg.python.org/peps/rev/a7b2b2d5b1d4

**Comment by myint** [comment]
Yeah, I remember that. Thanks for the reminder! I'm willing to accept a pull request to fix this.

**Comment by kapsh** [comment]
Personally I would prefer `--blank` as single option which accepts yes/no and defaults to no (there is possible disadvantage: breaking someone's automated tools with `no-blank` used). 

Thereby I suggest the following behavior:

* --blank yes OR --blank OR no argument = enable additional blank line.
* --blank no = disable additional blank line.
* --no-blank = disable additional blank line and emit a deprecation warning.

How it looks for you?

**Comment by myint** [comment]
I do see advantages to the `yes`/`no` style for configuration. But all the rest of the [options](https://github.com/myint/docformatter#options) already use the toggle style where the option turns the feature on. So I think I would prefer to just use `--blank` for uniformity.

I plan to increment the major version to 1.0 to indicate this interface change.

Thanks

**Comment by kapsh** [comment]
Makes sense and even easier.
I have another question then: I can replace argparse argument only or additionally change default values for `post_description_blank` arguments in functions. But 2nd option will require removing blank lines in tests, is it okay?

**Comment by kapsh** [comment]
All done in #20.

**Comment by madig** [comment]
I'd like to see a new release that ships this feature :) are there showstoppers left?

**Comment by myint** [comment]
Thanks for the reminder:

https://pypi.python.org/pypi/docformatter/1.0
