### ISSUE TITLE
Adds windows-style line endings to unix style file

### ISSUE THREAD

**Issue by youngmit** [myint/docformatter#22]
In Windows, when running docformatter on a file with unix-style line endings, it replaces all line endings with Windows-style endings. I assume it picks the type of line endings based on the OS, rather than the file, which is a pretty bad assumption. Other tools like autopep8 and yapf don't seem to have this issue.

**Comment by myint** [comment]
If I recall correctly, in `autopep8`, I explicitly added code to detect the most common line ending. Then right before writing out the transformed source code, I use that line ending to join the lines.
