### ISSUE TITLE
Add a `--check` flag to see if changes would be made.

### ISSUE THREAD

**Issue by dwayneyuen** [myint/docformatter#26]
I'd find it useful if this had a `--check`-like flag which doesn't modify the code but simply returns whether or not changes would be made (and returns an appropriate error code).

The motivation here is that the return code can be hooked up to test integration.

Other popular python formatters have some form of this kind of flag:
https://github.com/ambv/black
```
  --check                     Don't write the files back, just return the
                              status.  Return code 0 means nothing would
                              change.  Return code 1 means some files would be
                              reformatted.  Return code 123 means there was an
                              internal error.
```

https://github.com/timothycrosley/isort
```
Using isort to verify code
The --check-only option
isort can also be used to used to verify that code is correctly formatted by running it with -c. Any files that contain incorrectly sorted and/or formatted imports will be outputted to stderr.

isort **/*.py -c -vb

SUCCESS: /home/timothy/Projects/Open_Source/isort/isort_kate_plugin.py Everything Looks Good!
ERROR: /home/timothy/Projects/Open_Source/isort/isort/isort.py Imports are incorrectly sorted.
One great place this can be used is with a pre-commit git hook, such as this one by @acdha:

https://gist.github.com/acdha/8717683

This can help to ensure a certain level of code quality throughout a project
```

Thanks!

**Comment by kapsh** [comment]
I've tried to prototype this feature (kapsh@a15412b843b84316ed59bdbfea9007d34c482ebc), but it seems to raise some questions about subtle details.

Main idea is to return status codes for each file: ok, changed, needs to be changed, etc. Based on that `format_files` can decide what to tell user. Currently only `--check` changes it's behavior, but this can be easily extended if required.

Disputable points now. 
1. Should `--check` change exit code if docstrings were considered incorrect? I think yes, it's a common behavior for linters.
2. Should other modes change exit code? E.g. return non-zero if files were changed in place or diff was written to console.
2a. If yes, codes could be different or just simple `1` for any type of change. Users usually doesn't bother about exit codes, but they are convenient for fine CI tuning.
3. Does this apply to formatting stdin? Never used this feature and have no clue what others would expect here.

@myint I'm interested in your vision here (and yours @dwayneyuen of course).

**Comment by myint** [comment]
1. This sounds reasonable to me.
2. I think for other modes it makes sense to keep the existing behavior. Non-zero exit status is meant for reporting problems while modifying the files (`IOError`, etc.).

**Comment by kapsh** [comment]
Yeah, really. Console output is already feedbacky enough and if files were changed - that's what user wanted when running `-i`. But I see that `IOErrors` just reported currently without changing exit code and the only one special `return` is used for ctrl-c. 

I can pass all kind of results ("errors happened", "formatting is incorrect") into `main` in the consistent way.

**Comment by kapsh** [comment]
Please judge my approach in #32. Code and naming are clumsy, but main logic should be readable.
