### ISSUE TITLE
Publish a tag 

### ISSUE THREAD

**Issue by mxr** [myint/docformatter#33]
I was wondering if a tag could be created for a commit at 88b3a1901e03c7d370d33085363ffd9655e5a888 (or later). I'm using `docformatter` with [pre-commit](https://pre-commit.com) and I can point my config to use `docformatter` at 88b3a1901e03c7d370d33085363ffd9655e5a888, but if I could instead point to a tag, then `pre-commit autoupdate` would be able to pull in new updates as new releases/tags are published. Thanks!

**Comment by myint** [comment]
Sure, tagged and uploaded to [PyPI](https://pypi.org/project/docformatter/1.1/).

**Comment by mxr** [comment]
Thanks!
