### ISSUE TITLE
New Release of Docformatter - no support of -c (--check) in release 1.1

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [myint/docformatter#37]
Although documentation on site shows, that docformater supports check flag, the latest release of the docformatter (v 1.1. does not suppport this flag.) This makes it imposible for me to use docformatter on CI to check, whether some file need to be reformatted by docformatter, although such functionality is supported according to documentation.

Therefore, having a new version /release with support of this functionality would be of great help

**Comment by myint** [comment]
Sure!

https://pypi.org/project/docformatter/1.2/
