### ISSUE TITLE
--exclude flag

### ISSUE THREAD

**Issue by CanTuerk** [myint/docformatter#59]
Hello, 
I'm quite new to Github and all so forgive me if this is not the right section for this kind of problem.

I want to use docformatter for my project, I installed it with pip and everything works fine. 
My only problem is that I can't use the --exclude/-e flag, I saw that it was commited to this repository but I have no clue how to access it from here. Would love if somebody could help me out with this. 

With kind regards,
Can

**Comment by merwok** [comment]
That option was just added to the codebase, so you’ll have to wait for the next release then you’ll be able to update your install and use it :slightly_smiling_face:

**Comment by danieljanes** [comment]
Thanks @merwok, that's great. We're also eagerly waiting for that. Is there already an ETA for the next release?

**Comment by myint** [comment]
https://pypi.org/project/docformatter/1.4/
